(user/prontend) 파일 삭제 , 주석, 모의투자 누르면 로그인 모달창 띄우기
nbcamp-HappyMoney/HappyMoney pull request #138
Opened 2024-02-17 12:56 UTC by kimminjae981002

* 진행사항
1. google.js 파일 삭제
2. email 폴더 에서 spec,controller 파일 삭제
3. user.service 주석
4. email.service 주석
5. 소셜 로그인 주석
6. 모의투자 링크 누르면 로그인이 안 돼있을 때 로그인 모달창 띄우기

* 특이사항
1. 브라우저 닫을 시 로그아웃 기능 취소
- 이유: 대부분 사이트들이 브라우저 닫을 시에 로그아웃 상태로 남아있지 않음

2024-02-18 07:21 UTC, Geniusjun6 requested changes
안쓰는 코드는 삭제해주세여~

2024-02-18 07:21 UTC, Geniusjun6 commented on assets/js/common.js
>    if (token === "Bearer null") {
이거 안쓰면 그냥 삭제해주세요 주석처리 말고 ~

2024-02-18 07:21 UTC, Geniusjun6 commented on assets/js/stock-main.js
> +      // window.location.href = "/views/main.html";
이것도 안쓰는거면 주석 말고 삭제 부탁드립니다.

2024-02-19 00:00 UTC, kimminjae981002 commented on assets/js/stock-main.js
> +      // window.location.href = "/views/main.html";
완료했습니다~

2024-02-19 00:11 UTC, Geniusjun6 approved these changes
감사합니다.

2024-02-19 00:12 UTC, merged